---
- name: Clonar repo front
  git:
    repo: https://github.com/jehansel/DigitalHouse-ProyectoIntegrador-Team1-PetCare.git
    dest: /var/www/petcare-front
  become: true

- name: Clonar repo back
  git:
    repo: https://github.com/ricardocuellar/proyectoIntegradorBackend-team1.git
    dest: /var/www/petcare-back
  become: true
