---
- name: Instalar nvm
  ansible.builtin.shell: |
    export NVM_DIR="$HOME/.nvm"
    if [ ! -s "$NVM_DIR/nvm.sh" ]; then
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
    fi
  args:
    executable: /bin/bash
  become: true
  become_user: ubuntu

- name: Instalar Node.js versión 22
  ansible.builtin.shell: |
    export NVM_DIR="$HOME/.nvm"
    source $NVM_DIR/nvm.sh
    if ! nvm ls 22 > /dev/null 2>&1; then
      nvm install 22
    fi
  args:
    executable: /bin/bash
  become: true
  become_user: ubuntu

- name: Verificar instalación de Node.js
  ansible.builtin.shell: |
    export NVM_DIR="$HOME/.nvm"
    source $NVM_DIR/nvm.sh
    node -v
  args:
    executable: /bin/bash
  become: true
  become_user: ubuntu
  register: node_version

- name: Instalar NPM
  ansible.builtin.shell: |
    export NVM_DIR="$HOME/.nvm"
    source $NVM_DIR/nvm.sh
    nvm install-latest-npm
  args:
    executable: /bin/bash
  become: true
  become_user: ubuntu

- name: Mostrar versión de Node.js instalada
  ansible.builtin.debug:
    msg: "La versión de Node.js instalada es {{ node_version.stdout }}"

- name: Clonar repo front
  git:
    repo: https://github.com/jehansel/DigitalHouse-ProyectoIntegrador-Team1-PetCare.git ## https://github.com/Akaidmaru/DigitalHouse-ProyectoIntegrador-Team1-PetCare.git 
    dest: /var/www/petcare-front
    force: true
  become: true

- name: Cambiar permisos del directorio del front y sus archivos
  ansible.builtin.shell: |
    chown -R ubuntu:ubuntu /var/www/petcare-front
    chmod -R 755 /var/www/petcare-front
  args:
    executable: /bin/bash
  become: true

- name: Crear archivo .env con variables de entorno
  ansible.builtin.copy:
      dest: /var/www/petcare-front/.env
      content: |
          VITE_API_URL={{ VITE_API_URL  }}
      owner: ubuntu
      group: ubuntu
      mode: "0600"
  become: true

- name: Instalar dependencias del front (npm install)
  ansible.builtin.shell: |
    export NVM_DIR="$HOME/.nvm"
    source $NVM_DIR/nvm.sh
    npm install
  args:
    chdir: /var/www/petcare-front
    executable: /bin/bash
  become: true
  become_user: ubuntu

- name: Compilar front con Vite
  ansible.builtin.shell: |
    export NVM_DIR="$HOME/.nvm"
    source $NVM_DIR/nvm.sh
    npm run build
  args:
    chdir: /var/www/petcare-front
    executable: /bin/bash
  become: true
  become_user: ubuntu
