---
version: '3.8'

services:
  frontend:
    image: ghcr.io/akaidmaru/digitalhouse-proyectointegrador-team1-petcare:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: ghcr.io/akaidmaru/proyectointegradorbackend-team1:latest
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    ports:
      - "8080:8080"