---
- name: Install nvm
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: Restart bash # ERROR ACÁ, HAY QUE HACER CORRECCIÓN
  shell: |
    . ~/.bashrc
    nvm install node 22
  args:
    executable: /bin/bash
  register: nvm_install


- name: Verify Node.js Installation
  shell: node -v
  register: node_version
  become: false

- name: Verify NPM Installation
  shell: npm -v
  register: npm_version
  become: false

- name: Print Node.js and NPM versions
  debug:
    msg: "Node.js version is {{ node_version.stdout }} and NPM version is {{ npm_version.stdout }}"
