---

- name : Download and Install FNM
  shell: curl -o- https://fnm.vercel.app/install | bash
  become: false

- name: Add fnm to path
  shell: echo 'export PATH="$HOME/.fnm:PATH"' >> ~/.bashrc
  become: false

- name: Reload shell
  shell: source ~/.bashrc
  become: false

- name : Install Node.js
  shell: ~/.fnm/fnm install 22
  become: false

- name : Verify Node.js Installation
  shell: node -v
  register: node_version
  become: false

- name : Verify NPM Installation
  shell: npm -v
  register: npm_version
  become: false

- name : Print Node.js and NPM versions
  debug:
    msg: "Node.js version is {{ node_version.stdout }} and NPM version is {{ npm_version.stdout }}"
