---
- name : Install Nginx
  apt:
    name: nginx
    state: present

- name: Crear directorio para el front en Nginx
  ansible.builtin.file:
    path: /var/www/html/petcare-front
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  become: true

- name: Copiar contenido de la carpeta dist a /var/www/html/petcare-front
  ansible.builtin.shell: cp -r /var/www/petcare-front/dist/* /var/www/html/petcare-front/
  become: true

- name: Eliminar el archivo default de Nginx
  ansible.builtin.file: 
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: true

- name: Configurar Nginx para servir el front
  ansible.builtin.template:
    src: petcare-front.j2
    dest: /etc/nginx/sites-available/petcare-front
  become: true

- name: Habilitar la configuración de Nginx para el front
  ansible.builtin.file:
    src: /etc/nginx/sites-available/petcare-front
    dest: /etc/nginx/sites-enabled/petcare-front
    state: link
  become: true

- name: Reiniciar Nginx para aplicar cambios
  ansible.builtin.service:
    name: nginx
    state: restarted
  become: true
